package com.sl.wholesale.entity.hibernate;

// Generated 2016-12-23 23:53:14 by Hibernate Tools 4.0.0

import java.util.Date;

import com.sl.global.entity.BaseEntity;

/**
 * Company generated by hbm2java
 */
public class Company extends BaseEntity implements java.io.Serializable {

	private Long id;
	private String name;
	private String phone;
	private String address;
	private String url;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private UserInfo userInfo;

	public Company() {
	}

	public Company(Date createDate, Date updateDate) {
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Company(String name, String phone, String address, String url,
			Date createDate, Date updateDate, Integer state, UserInfo userInfo) {
		this.name = name;
		this.phone = phone;
		this.address = address;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.userInfo = userInfo;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

}
