package com.sl.wholesale.entity.hibernate;

// Generated 2016-12-30 16:19:21 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sl.global.entity.BaseEntity;

/**
 * Goods generated by hbm2java
 */
public class Goods extends BaseEntity implements java.io.Serializable {

	private Long id;
	private GoodsType goodsType;
	private String name;
	private String spec;
	private String brand;
	private String provider;
	private String url;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set items = new HashSet(0);

	public Goods() {
	}

	public Goods(Date createDate, Date updateDate) {
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Goods(GoodsType goodsType, String name, String spec, String brand,
			String provider, String url, Date createDate, Date updateDate,
			Integer state, Set items) {
		this.goodsType = goodsType;
		this.name = name;
		this.spec = spec;
		this.brand = brand;
		this.provider = provider;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.items = items;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public GoodsType getGoodsType() {
		return this.goodsType;
	}

	public void setGoodsType(GoodsType goodsType) {
		this.goodsType = goodsType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
