package com.sl.wholesale.entity.hibernate;

// Generated 2017-1-19 16:12:52 by Hibernate Tools 4.0.0

import com.sl.global.entity.BaseEntity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 			@description entity generated by hbm2java.
 * 			@author LAVEN
 * 			@since JDK 1.7 
 * 	    
 */
public class Goods extends BaseEntity implements java.io.Serializable {

	private Long id;
	private GoodsType goodsType;
	/**
	 * 物资名称
	 */
	private String name = "";
	/**
	 * 物资规格
	 */
	private String spec = "";
	/**
	 * 物资品牌
	 */
	private String brand = "";
	/**
	 * 物资供应商
	 */
	private String provider = "";
	/**
	 * 物资图片
	 */
	private String url = "";
	private Date createDate = new Date();
	private Date updateDate = new Date();
	/**
	 * 数据状态(1:有效；0删除)
	 */
	private Integer state = 1;
	private Set prices = new HashSet(0);

	public Goods() {
	}

	public Goods(GoodsType goodsType, String name, String spec, String brand,
			String provider, String url, Date createDate, Date updateDate,
			Integer state, Set prices) {
		this.goodsType = goodsType;
		this.name = name;
		this.spec = spec;
		this.brand = brand;
		this.provider = provider;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.prices = prices;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public GoodsType getGoodsType() {
		return this.goodsType;
	}

	public void setGoodsType(GoodsType goodsType) {
		this.goodsType = goodsType;
	}

	/**       
	 *      * 物资名称
	 */
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**       
	 *      * 物资规格
	 */
	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	/**       
	 *      * 物资品牌
	 */
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	/**       
	 *      * 物资供应商
	 */
	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	/**       
	 *      * 物资图片
	 */
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**       
	 *      * 数据状态(1:有效；0删除)
	 */
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getPrices() {
		return this.prices;
	}

	public void setPrices(Set prices) {
		this.prices = prices;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("name").append("='").append(getName()).append("' ");
		buffer.append("spec").append("='").append(getSpec()).append("' ");
		buffer.append("brand").append("='").append(getBrand()).append("' ");
		buffer.append("provider").append("='").append(getProvider())
				.append("' ");
		buffer.append("state").append("='").append(getState()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Goods))
			return false;
		Goods castOther = (Goods) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getSpec() == castOther.getSpec()) || (this.getSpec() != null
						&& castOther.getSpec() != null && this.getSpec()
						.equals(castOther.getSpec())))
				&& ((this.getBrand() == castOther.getBrand()) || (this
						.getBrand() != null && castOther.getBrand() != null && this
						.getBrand().equals(castOther.getBrand())))
				&& ((this.getProvider() == castOther.getProvider()) || (this
						.getProvider() != null
						&& castOther.getProvider() != null && this
						.getProvider().equals(castOther.getProvider())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getSpec() == null ? 0 : this.getSpec().hashCode());
		result = 37 * result
				+ (getBrand() == null ? 0 : this.getBrand().hashCode());
		result = 37 * result
				+ (getProvider() == null ? 0 : this.getProvider().hashCode());

		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());

		return result;
	}

}
