package com.sl.wholesale.entity.hibernate;

// Generated 2016-12-23 23:53:14 by Hibernate Tools 4.0.0

import java.util.Date;

import com.sl.global.entity.BaseEntity;

/**
 * Item generated by hbm2java
 */
public class Item extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Goods goods;
	private Order order;
	private SaleMode saleMode;
	private Integer num;
	private Date createDate;
	private Date updateDate;
	private Integer state;

	public Item() {
	}

	public Item(Date createDate, Date updateDate) {
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Item(Goods goods, Order order, SaleMode saleMode, Integer num,
			Date createDate, Date updateDate, Integer state) {
		this.goods = goods;
		this.order = order;
		this.saleMode = saleMode;
		this.num = num;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public SaleMode getSaleMode() {
		return this.saleMode;
	}

	public void setSaleMode(SaleMode saleMode) {
		this.saleMode = saleMode;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
