package com.sl.wholesale.entity.hibernate;

// Generated 2017-1-19 16:12:52 by Hibernate Tools 4.0.0

import com.sl.global.entity.BaseEntity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 			@description entity generated by hbm2java.
 * 			@author LAVEN
 * 			@since JDK 1.7 
 * 	    
 */
public class Order extends BaseEntity implements java.io.Serializable {

	private Long id;
	private UserInfo userInfoByPurchase;
	private UserInfo userInfoBySale;
	/**
	 * 订单编号
	 */
	private String orderCode = "";
	/**
	 * 计算金额
	 */
	private double sumMoney = 0;
	/**
	 * 交易金额
	 */
	private double money = 0;
	private Date createDate = new Date();
	private Date updateDate = new Date();
	/**
	 * 数据状态(1:有效；0删除)
	 */
	private Integer state = 1;
	private Set orderDetails = new HashSet(0);

	public Order() {
	}

	public Order(UserInfo userInfoByPurchase, UserInfo userInfoBySale,
			String orderCode, double sumMoney, double money, Date createDate,
			Date updateDate, Integer state, Set orderDetails) {
		this.userInfoByPurchase = userInfoByPurchase;
		this.userInfoBySale = userInfoBySale;
		this.orderCode = orderCode;
		this.sumMoney = sumMoney;
		this.money = money;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.orderDetails = orderDetails;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public UserInfo getUserInfoByPurchase() {
		return this.userInfoByPurchase;
	}

	public void setUserInfoByPurchase(UserInfo userInfoByPurchase) {
		this.userInfoByPurchase = userInfoByPurchase;
	}

	public UserInfo getUserInfoBySale() {
		return this.userInfoBySale;
	}

	public void setUserInfoBySale(UserInfo userInfoBySale) {
		this.userInfoBySale = userInfoBySale;
	}

	/**       
	 *      * 订单编号
	 */
	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**       
	 *      * 计算金额
	 */
	public double getSumMoney() {
		return this.sumMoney;
	}

	public void setSumMoney(double sumMoney) {
		this.sumMoney = sumMoney;
	}

	/**       
	 *      * 交易金额
	 */
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**       
	 *      * 数据状态(1:有效；0删除)
	 */
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("orderCode").append("='").append(getOrderCode())
				.append("' ");
		buffer.append("sumMoney").append("='").append(getSumMoney())
				.append("' ");
		buffer.append("money").append("='").append(getMoney()).append("' ");
		buffer.append("state").append("='").append(getState()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Order))
			return false;
		Order castOther = (Order) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getOrderCode() == castOther.getOrderCode()) || (this
						.getOrderCode() != null
						&& castOther.getOrderCode() != null && this
						.getOrderCode().equals(castOther.getOrderCode())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		result = 37 * result
				+ (getOrderCode() == null ? 0 : this.getOrderCode().hashCode());

		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());

		return result;
	}

}
