package com.sl.wholesale.entity.hibernate;

// Generated 2017-1-19 16:12:52 by Hibernate Tools 4.0.0

import com.sl.global.entity.BaseEntity;
import java.util.Date;

/**
 * 			@description entity generated by hbm2java.
 * 			@author LAVEN
 * 			@since JDK 1.7 
 * 	    
 */
public class OrderDetail extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Goods goods;
	private Order order;
	private SaleMode saleMode;
	/**
	 * 项目数量
	 */
	private Integer num = 0;
	/**
	 * 项目单价
	 */
	private double price = 0;
	/**
	 * 计算金额
	 */
	private double sumMoney = 0;
	/**
	 * 交易金额
	 */
	private double money = 0;
	private Date createDate = new Date();
	private Date updateDate = new Date();
	/**
	 * 数据状态(1:有效；0删除)
	 */
	private Integer state = 1;

	public OrderDetail() {
	}

	public OrderDetail(Goods goods, Order order, SaleMode saleMode,
			Integer num, double price, double sumMoney, double money,
			Date createDate, Date updateDate, Integer state) {
		this.goods = goods;
		this.order = order;
		this.saleMode = saleMode;
		this.num = num;
		this.price = price;
		this.sumMoney = sumMoney;
		this.money = money;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public SaleMode getSaleMode() {
		return this.saleMode;
	}

	public void setSaleMode(SaleMode saleMode) {
		this.saleMode = saleMode;
	}

	/**       
	 *      * 项目数量
	 */
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	/**       
	 *      * 项目单价
	 */
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	/**       
	 *      * 计算金额
	 */
	public double getSumMoney() {
		return this.sumMoney;
	}

	public void setSumMoney(double sumMoney) {
		this.sumMoney = sumMoney;
	}

	/**       
	 *      * 交易金额
	 */
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**       
	 *      * 数据状态(1:有效；0删除)
	 */
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("num").append("='").append(getNum()).append("' ");
		buffer.append("price").append("='").append(getPrice()).append("' ");
		buffer.append("sumMoney").append("='").append(getSumMoney())
				.append("' ");
		buffer.append("money").append("='").append(getMoney()).append("' ");
		buffer.append("state").append("='").append(getState()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetail))
			return false;
		OrderDetail castOther = (OrderDetail) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getNum() == castOther.getNum()) || (this.getNum() != null
						&& castOther.getNum() != null && this.getNum().equals(
						castOther.getNum())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		result = 37 * result
				+ (getNum() == null ? 0 : this.getNum().hashCode());

		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
