package com.sl.wholesale.entity.hibernate;

// Generated 2017-1-9 19:54:26 by Hibernate Tools 4.0.0

import java.util.Date;

import com.sl.global.entity.BaseEntity;

/**
 * Price generated by hbm2java
 */
public class Price extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Goods goods;
	private SaleMode saleMode;
	private double price;
	private double weight;
	private double money;
	private Date createDate;
	private Date updateDate;
	private Integer state;

	public Price() {
	}

	public Price(Date createDate, Date updateDate) {
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Price(Goods goods, SaleMode saleMode, double price, double weight,
			double money, Date createDate, Date updateDate, Integer state) {
		this.goods = goods;
		this.saleMode = saleMode;
		this.price = price;
		this.weight = weight;
		this.money = money;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public SaleMode getSaleMode() {
		return this.saleMode;
	}

	public void setSaleMode(SaleMode saleMode) {
		this.saleMode = saleMode;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public double getWeight() {
		return this.weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
