package com.sl.wholesale.entity.hibernate;

// Generated 2016-12-30 16:19:21 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sl.global.entity.BaseEntity;

/**
 * SaleMode generated by hbm2java
 */
public class SaleMode extends BaseEntity implements java.io.Serializable {

	private Long id;
	private String name;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set items = new HashSet(0);

	public SaleMode() {
	}

	public SaleMode(Date createDate, Date updateDate) {
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public SaleMode(String name, Date createDate, Date updateDate,
			Integer state, Set items) {
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.items = items;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
