package com.sl.wholesale.entity.hibernate;

// Generated 2016-10-27 14:37:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WsCompany generated by hbm2java
 */
public class WsCompany implements java.io.Serializable {

	private long id;
	private String companyName;
	private String phone;
	private String address;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private WsUserInfo wsUserInfo;

	public WsCompany() {
	}

	public WsCompany(long id, Date createDate, Date updateDate) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public WsCompany(long id, String companyName, String phone, String address,
			Date createDate, Date updateDate, Integer state,
			WsUserInfo wsUserInfo) {
		this.id = id;
		this.companyName = companyName;
		this.phone = phone;
		this.address = address;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.wsUserInfo = wsUserInfo;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public WsUserInfo getWsUserInfo() {
		return this.wsUserInfo;
	}

	public void setWsUserInfo(WsUserInfo wsUserInfo) {
		this.wsUserInfo = wsUserInfo;
	}

}
