package com.sl.wholesale.entity.hibernate;

// Generated 2016-10-27 14:37:02 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WsGoods generated by hbm2java
 */
public class WsGoods implements java.io.Serializable {

	private long id;
	private WsGoodsType wsGoodsType;
	private String name;
	private String spec;
	private String brand;
	private String provider;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set wsItems = new HashSet(0);

	public WsGoods() {
	}

	public WsGoods(long id, Date createDate, Date updateDate) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public WsGoods(long id, WsGoodsType wsGoodsType, String name, String spec,
			String brand, String provider, Date createDate, Date updateDate,
			Integer state, Set wsItems) {
		this.id = id;
		this.wsGoodsType = wsGoodsType;
		this.name = name;
		this.spec = spec;
		this.brand = brand;
		this.provider = provider;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.wsItems = wsItems;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public WsGoodsType getWsGoodsType() {
		return this.wsGoodsType;
	}

	public void setWsGoodsType(WsGoodsType wsGoodsType) {
		this.wsGoodsType = wsGoodsType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getWsItems() {
		return this.wsItems;
	}

	public void setWsItems(Set wsItems) {
		this.wsItems = wsItems;
	}

}
