package com.sl.wholesale.entity.hibernate;

// Generated 2016-10-27 14:37:02 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * WsItem generated by hbm2java
 */
public class WsItem implements java.io.Serializable {

	private long id;
	private WsGoods wsGoods;
	private WsOrder wsOrder;
	private WsSaleMode wsSaleMode;
	private Integer num;
	private Date createDate;
	private Date updateDate;
	private Integer state;

	public WsItem() {
	}

	public WsItem(long id, Date createDate, Date updateDate) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public WsItem(long id, WsGoods wsGoods, WsOrder wsOrder,
			WsSaleMode wsSaleMode, Integer num, Date createDate,
			Date updateDate, Integer state) {
		this.id = id;
		this.wsGoods = wsGoods;
		this.wsOrder = wsOrder;
		this.wsSaleMode = wsSaleMode;
		this.num = num;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public WsGoods getWsGoods() {
		return this.wsGoods;
	}

	public void setWsGoods(WsGoods wsGoods) {
		this.wsGoods = wsGoods;
	}

	public WsOrder getWsOrder() {
		return this.wsOrder;
	}

	public void setWsOrder(WsOrder wsOrder) {
		this.wsOrder = wsOrder;
	}

	public WsSaleMode getWsSaleMode() {
		return this.wsSaleMode;
	}

	public void setWsSaleMode(WsSaleMode wsSaleMode) {
		this.wsSaleMode = wsSaleMode;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
