package com.sl.wholesale.entity.hibernate;

// Generated 2016-10-27 14:37:02 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WsOrder generated by hbm2java
 */
public class WsOrder implements java.io.Serializable {

	private long id;
	private WsUserInfo wsUserInfoByPurchase;
	private WsUserInfo wsUserInfoBySale;
	private BigDecimal sumMoney;
	private BigDecimal money;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set wsItems = new HashSet(0);

	public WsOrder() {
	}

	public WsOrder(long id, Date createDate, Date updateDate) {
		this.id = id;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public WsOrder(long id, WsUserInfo wsUserInfoByPurchase,
			WsUserInfo wsUserInfoBySale, BigDecimal sumMoney, BigDecimal money,
			Date createDate, Date updateDate, Integer state, Set wsItems) {
		this.id = id;
		this.wsUserInfoByPurchase = wsUserInfoByPurchase;
		this.wsUserInfoBySale = wsUserInfoBySale;
		this.sumMoney = sumMoney;
		this.money = money;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.wsItems = wsItems;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public WsUserInfo getWsUserInfoByPurchase() {
		return this.wsUserInfoByPurchase;
	}

	public void setWsUserInfoByPurchase(WsUserInfo wsUserInfoByPurchase) {
		this.wsUserInfoByPurchase = wsUserInfoByPurchase;
	}

	public WsUserInfo getWsUserInfoBySale() {
		return this.wsUserInfoBySale;
	}

	public void setWsUserInfoBySale(WsUserInfo wsUserInfoBySale) {
		this.wsUserInfoBySale = wsUserInfoBySale;
	}

	public BigDecimal getSumMoney() {
		return this.sumMoney;
	}

	public void setSumMoney(BigDecimal sumMoney) {
		this.sumMoney = sumMoney;
	}

	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getWsItems() {
		return this.wsItems;
	}

	public void setWsItems(Set wsItems) {
		this.wsItems = wsItems;
	}

}
