package com.sl.wholesale.entity.hibernate;

// Generated 2016-10-27 14:37:02 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sl.base.entity.hibernate.BaseUser;

/**
 * WsUserInfo generated by hbm2java
 */
public class WsUserInfo implements java.io.Serializable {

	private long id;
	private BaseUser baseUser;
	private WsCompany wsCompany;
	private long companyId;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set wsOrdersForSale = new HashSet(0);
	private Set wsOrdersForPurchase = new HashSet(0);

	public WsUserInfo() {
	}

	public WsUserInfo(BaseUser baseUser, WsCompany wsCompany, long companyId,
			Date createDate, Date updateDate) {
		this.baseUser = baseUser;
		this.wsCompany = wsCompany;
		this.companyId = companyId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public WsUserInfo(BaseUser baseUser, WsCompany wsCompany, long companyId,
			Date createDate, Date updateDate, Integer state,
			Set wsOrdersForSale, Set wsOrdersForPurchase) {
		this.baseUser = baseUser;
		this.wsCompany = wsCompany;
		this.companyId = companyId;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.wsOrdersForSale = wsOrdersForSale;
		this.wsOrdersForPurchase = wsOrdersForPurchase;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public BaseUser getBaseUser() {
		return this.baseUser;
	}

	public void setBaseUser(BaseUser baseUser) {
		this.baseUser = baseUser;
	}

	public WsCompany getWsCompany() {
		return this.wsCompany;
	}

	public void setWsCompany(WsCompany wsCompany) {
		this.wsCompany = wsCompany;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getWsOrdersForSale() {
		return this.wsOrdersForSale;
	}

	public void setWsOrdersForSale(Set wsOrdersForSale) {
		this.wsOrdersForSale = wsOrdersForSale;
	}

	public Set getWsOrdersForPurchase() {
		return this.wsOrdersForPurchase;
	}

	public void setWsOrdersForPurchase(Set wsOrdersForPurchase) {
		this.wsOrdersForPurchase = wsOrdersForPurchase;
	}

}
