package com.sl.base.entity.hibernate;

// Generated 2016-10-27 14:31:25 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BaseUser generated by hbm2java
 */
public class BaseUser implements java.io.Serializable {

	private long id;
	private BaseRole baseRole;
	private String username;
	private String password;
	private String phone;
	private Date createDate;
	private Date updateDate;
	private Integer state;

	public BaseUser() {
	}

	public BaseUser(long id, BaseRole baseRole, String username,
			String password, Date createDate, Date updateDate) {
		this.id = id;
		this.baseRole = baseRole;
		this.username = username;
		this.password = password;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public BaseUser(long id, BaseRole baseRole, String username,
			String password, String phone, Date createDate, Date updateDate,
			Integer state) {
		this.id = id;
		this.baseRole = baseRole;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public BaseRole getBaseRole() {
		return this.baseRole;
	}

	public void setBaseRole(BaseRole baseRole) {
		this.baseRole = baseRole;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
