package com.sl.base.entity.hibernate;

// Generated 2016-12-23 16:52:00 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sl.global.entity.BaseEntity;

/**
 * Role generated by hbm2java
 */
public class Role extends BaseEntity implements java.io.Serializable {

	private Long id;
	private String name;
	private String url;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(String name, Date createDate, Date updateDate) {
		this.name = name;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Role(String name, String url, Date createDate, Date updateDate,
			Integer state, Set users) {
		this.name = name;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.users = users;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
