package com.sl.portal.entity.hibernate;

// Generated 2017-1-19 16:12:52 by Hibernate Tools 4.0.0

import com.sl.global.entity.BaseEntity;
import java.util.Date;

/**
 * 			@description entity generated by hbm2java.
 * 			@author LAVEN
 * 			@since JDK 1.7 
 * 	    
 */
public class User extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Role role;
	/**
	 * 用户名称
	 */
	private String username = "";
	/**
	 * 用户密码
	 */
	private String password = "";
	/**
	 * 用户电话
	 */
	private String phone = "";
	/**
	 * 角色头像
	 */
	private String url = "";
	private Date createDate = new Date();
	private Date updateDate = new Date();
	/**
	 * 数据状态(1:有效；0删除)
	 */
	private Integer state = 1;

	public User() {
	}

	public User(Role role) {
		this.role = role;
	}

	public User(Role role, String username, String password, String phone,
			String url, Date createDate, Date updateDate, Integer state) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	/**       
	 *      * 用户名称
	 */
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/**       
	 *      * 用户密码
	 */
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/**       
	 *      * 用户电话
	 */
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**       
	 *      * 角色头像
	 */
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**       
	 *      * 数据状态(1:有效；0删除)
	 */
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("username").append("='").append(getUsername())
				.append("' ");
		buffer.append("phone").append("='").append(getPhone()).append("' ");
		buffer.append("state").append("='").append(getState()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof User))
			return false;
		User castOther = (User) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null && castOther.getState() != null && this
						.getState().equals(castOther.getState())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());

		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		return result;
	}

}
