package com.sl.portal.entity.hibernate;

// Generated 2016-12-23 23:54:11 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.sl.global.entity.BaseEntity;

/**
 * User generated by hbm2java
 */
public class User extends BaseEntity implements java.io.Serializable {

	private Long id;
	private Role role;
	private String username;
	private String password;
	private String phone;
	private String url;
	private Date createDate;
	private Date updateDate;
	private Integer state;
	private Set userInfos = new HashSet(0);

	public User() {
	}

	public User(Role role, String username, String password, Date createDate,
			Date updateDate) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public User(Role role, String username, String password, String phone,
			String url, Date createDate, Date updateDate, Integer state,
			Set userInfos) {
		this.role = role;
		this.username = username;
		this.password = password;
		this.phone = phone;
		this.url = url;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.state = state;
		this.userInfos = userInfos;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Set getUserInfos() {
		return this.userInfos;
	}

	public void setUserInfos(Set userInfos) {
		this.userInfos = userInfos;
	}

}
